version: '2'
services:
  dockerclean:
    image: docker
    read_only: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - $PWD/run/scripts/usr-local-bin/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh
    network_mode: none
